language: python

python:
    - "3.6"

before_install:
  -  sudo apt-get install libzbar-dev
install:
  - pip install .

script:
  - pytest

branches:
  only:
    - master

notifications:
    email: sa