language: python

python:
  - "3.6"

# Setup Test Environment
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - pip install .

script:
  - pytest --cov=grafeo

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
    email: sa
